### ISSUE TITLE
Relax alignment requirements

### ISSUE THREAD

**Issue by codener** [makandra/makandra-rubocop#7]
This little method tries to parse a date from request parameters and falls back to "today":
```
def set_date
  @date = begin
    Date.parse(params[:date])
  rescue TypeError, ArgumentError
    Date.today
  end
end
```
However, Rubocop complains that `rescue` doesn't align with `begin`. While this satiesfies it (WAT) ...
```
def set_date
  @date = begin
    Date.parse(params[:date])
          rescue TypeError, ArgumentError
            Date.today
  end
end
```
... probably this is what Rubocop wants:
```
def set_date
  @date = begin
            Date.parse(params[:date])
          rescue TypeError, ArgumentError
            Date.today
          end
  end
```

This huge indentation is no good thing. It denies the "indent with 2 spaces" principle and worse, it makes many lines depend on a single other line: when the `@date` variable is renamed, all the lines below need to be rearranged.

## Verdict
Rubocop should not force `begin` and `rescue` to align. There's nothing wrong in the first code example.

Probably there are related alignment rules that need to be adapted similarly.

**Comment by foobear** [comment]
To clarify: The cop in question is [Layout/RescueEnsureAlignment](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/RescueEnsureAlignment).

And yes, you are right, Rubocop's layout cops default to aligning the entire statement, as outlined in your 3rd code block. While the 2nd code block satisfies the cop, we definitely would not want that.

The cop's actual intention is still valid: `rescue` must be outdented. We would want to enforce this since there is never a reason to indent `rescue` like the code it rescues errors from.
However, the cop is missing an option to like `variable` for `Layout/EndAlignment`.

Since this is an issue in Rubocop, we should disable the cop for now. Please open an issue on the rubocop repo to introduce an extra option to support beginning-of-line-alignment in future versions.

If you suggest disabling further cops, please name them explicitly. Other cops, like [EndAlignment](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/EndAlignment), work as expected.

**Comment by codener** [comment]
There is an issue on this topic https://github.com/rubocop-hq/rubocop/issues/6254. While its fix was released in 0.64 https://github.com/rubocop-hq/rubocop/pull/6753, it still has problems which haven't been fixed yet https://github.com/rubocop-hq/rubocop/pull/6771.

Need to have an eye on this and update our fork once that thing is straight.

**Comment by foobear** [comment]
Cop has been disabled in 3.1.0

**Comment by foobear** [comment]
Once Rubocop's related issues have been resolved, we will open a new issue for discussion if we want to re-enable the cop with a different configuration.
